=begin pod

=head1 NAME

B<THIS IS A WORK IN PROGRESS>

B<Raku::Lint>

Checks for some mistakes in Raku files and modules. Currently checks for:

=item matching pod C<=begin/=end> statements

=item matching file C<open/close> statements

=item matching heredoc labels

It also detects some Perl constructs that are lurking during a port
of Perl code to Raku such as:

=item foreach

=item heredocs using '<<'

=head1 SYNOPSIS

=begin code :lang<raku>
    raku-lint [options...] <file names...>
=end code

=head1 DESCRIPTION

This module is a simple checker of Raku source code to detect common
coding errors (file scope only at present). Its advantage over the compiler is that it checks every
line rather than bailing out after finding the first error. 
It can be very useful in porting Perl code to Raku, and it may eventually use
some code from B<Larry Wall>'s and B<Bruce Gray>'s old conversion programs.

The module includes the executable Raku program C<raku-lint>.  Its
use is shown by executing it with no arguments, e.g.,

=begin code :lang<raku>
$ ./raku-lint
Usage: raku-lint [options...] <one or more files to check...>

Checks files for errors:

  matching =begin/=end blocks
  file opens without a close

Options:

  --file=X   Files listed in file X are added to the list of files
               to check.
  --verbose  Reports more details to stdout.
=end code

=head1 AUTHOR

Tom Browder <tbrowder@cpan.org>

=head1 COPYRIGHT and LICENSE

Copyright © 2021 Tom Browder

This library is free software; you may redistribute or modify it under
the Artistic License 2.0.

=end pod
