=begin pod

=head1 NAME

B<Raku::Lint> [B<THIS IS A WORK IN PROGRESS>]

A simple linter for Raku code

=head1 SYNOPSIS

=begin code :lang<raku>
$ ./raku-lint [options...] <file names...>
=end code

=head1 DESCRIPTION

This module is a simple checker of Raku source code to detect common
coding errors (file scope only at present). Its advantage over the
compiler is that it checks every line rather than bailing out after
finding the first error.  It can be very useful in porting Perl code
to Raku, and it may eventually use some code from B<Larry Wall>'s and
B<Bruce Gray>'s old conversion programs as well as the late B<Jeff Goff>'s
B<Perl6::Parser>.

The module includes the executable Raku program C<raku-lint>.  Its use
is shown by executing it with no arguments, e.g.,

=begin code :lang<raku>
$ ./raku-lint
Usage: lint.raku [options...] <files to check...>

Checks files for some syntax and other errors.

Options:

  --dir=X       Raku files listed in directory X are added to the
                  list of files to check.
  --file=X      Files listed in file X are added to the list of files
                  to check.
  --strip       Strips normal comments (at and following first '#'
                  character on a line).
  --strip-last  Strips normal comments (at and following last '#'
                  character on a line).
  --verbose     Reports findings in detail to stdout.
=end code

Currently checks for:

=begin item
Pod blocks

Matching pod C<=begin/=end> statements (checks for same indentation)

Runaway pod blocks (improperly closed blocks).
=end item

=item Matching file C<open/close> statements

=begin item
Heredocs

Matching terminators

Runaway heredocs (missing ending terminator)

Lines with less indentation than the terminator
=end item

It also detects some Perl constructs that are lurking during a port
of Perl code to Raku such as:

=item foreach

=item heredocs using '=<<'

=head1 AUTHOR

Tom Browder <tbrowder@cpan.org>

=head1 COPYRIGHT and LICENSE

Copyright © 2021 Tom Browder

This library is free software; you may redistribute or modify it under
the Artistic License 2.0.

=end pod
